#!/usr/bin/env python3
a= [2, 2, 2, 8, 8, 0, 4]
for i in range(len(a)-1):
    if(a[i]==a[i+1]):
        a[i]=a[i]+a[i+1]
        a[i+1]=0
print("Unsorted output:"+ str(a))
a.sort(key=lambda a: a != 0, reverse=True)
print("sorted output:"+ str(a))
 
